version: "3.9"

services:
  api:
    container_name: api-service
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4040:4040
    environment:
      - debugMode:${debugMode}
    volumes:
      - /src
      - .:/src
